# Use root/example as user/password credentials
version: '3.1'

volumes:
  local_pg_data: {}
#  local_mongo_data_backups: {}

services:
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog_gsb_forms
    ports:
      - '8025:8025'
      - '1025:1025'
